[package]
name = "tera-proxy"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "tera-proxy"
path = "src/main.rs"

[dependencies]
tera-protocol = { workspace = true }
tera-hook = { workspace = true }
anyhow = { workspace = true }
socket2 = { workspace = true }
clap = { workspace = true }
libloading = "0.8"
eframe = { version = "0.29", optional = true }

[features]
gui = ["dep:eframe"]
